name: Windows

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:

    runs-on: windows-latest
    
    strategy:
      fail-fast: false
      matrix:
        bits: [32, 64]
        include:
        - bits: 32
          ARCH: "i686"
          COMPILER_PATH: "C:\\msys64\\mingw32\\bin"
          
        - bits: 64
          ARCH: "x86_64"
          COMPILER_PATH: "C:\\msys64\\mingw64\\bin"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: "recursive"
    
    - name: Install CMake
      uses: Symbitic/install-cmake@v0.1.0
      with:
        cmake: "3.14.4"
        
    - name: Setup BUILD_32 ON
      run: |
        echo "::set-env name=BUILD_32::ON"
        echo "::set-env name=BUILD_BITS::32"
      shell: bash
      if: matrix.bits == 32
    
    - name: Setup BUILD_32 OFF
      run: |
        echo "::set-env name=BUILD_32::OFF"
        echo "::set-env name=BUILD_BITS::64"
      shell: bash
      if: matrix.bits == 64
    
    - name: Setup compiler
      run: |
        echo "::set-env name=CC::${{ matrix.ARCH }}-w64-mingw32-gcc.exe"
        echo "::set-env name=CXX::${{ matrix.ARCH }}-w64-mingw32-g++.exe"
      shell: bash
        
    - name: Run CMake
      run: |
        set PATH=%PATH%;${{ matrix.COMPILER_PATH }}
        cd "${{ github.workspace }}"
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug -DSTRESS_GC=ON -DBUILD_32="${{ env.BUILD_32 }}" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -G "MinGW Makefiles" ../
      shell: cmd
    
    - name: Run Make
      run: |
        set PATH=%PATH%;${{ matrix.COMPILER_PATH }}
        cd "${{ github.workspace }}\\build"
        mingw32-make
      shell: cmd
      
    - name: Print version
      run: |
        cd "${{ github.workspace }}\\build"
        melon.exe -v
      shell: cmd
    
    - name: Run Tests
      run: |
        cd "${{ github.workspace }}\\tests"
        ..\\build\\tests.exe
      shell: cmd
